apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ri448j17s-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ri448j17s-dotnet-basic-gitops